apiVersion: vpcaccess.cnrm.cloud.google.com/v1beta1
kind: VPCAccessConnector
metadata:
  name: run-vpc-access-connector
  namespace: networking
spec:
  location: "northamerica-northeast1" # kpt-set: ${gpc-region}
  machineType: "e2-micro"
  minInstances: 2
  maxInstances: 3
  subnet:
    nameRef:
      name: project-id-vpc-subnetwork-1 # kpt-set: ${project-id}-vpc-subnetwork-1
    projectRef:
      external: "000000000000" # kpt-set: projects/${project-id}
  projectRef:
    external: "00000000000" # kpt-set: ${project-id}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: project-id-vpc-subnetwork-1 # kpt-set: ${project-id}-vpc-subnetwork-1
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  ipCidrRange: "10.4.0.0/28"
  region: "northamerica-northeast1" # kpt-set: ${gcp-region}
  networkRef:
    name: project-id-vpc-network-1 # kpt-set: ${project-id}-vpc-network-1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: project-id-vpc-network-1 # kpt-set: ${project-id}-vpc-network-1
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  autoCreateSubnetworks: false