# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: runservice-sample
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: "northamerica-northeast1"
  projectRef:
    external:  '00000000000' # kpt-set: ${project-id}
  template:
    containers:
      - env:
          - name: "FOO"
            value: "bar"
        image: "..." # kpt-set: ${app-image}
    scaling:
      maxInstanceCount: 2
    vpcAccess:
      connectorRef:
        external:  # kpt-set: projects/${project-id}/locations/${gcp-region}/connectors/run-vpc-access-connector
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: allow-all-users
spec:
  resourceRef:
    name: runservice-sample
    kind: RunService
  bindings:
    - role: roles/run.invoker
      members:
        - member: allUsers